default:
  image: harbor.seacloud.garenanow.com/sail/python_bazel_golden:latest
  tags:
    - sail
  before_script:
    - python3 -m pip config set global.index-url http://pypi.ai.seacloud.garenanow.com/root/dev
    - python3 -m pip config set global.trusted-host pypi.ai.seacloud.garenanow.com

stages:
  - lint
  - build_and_test
  - deploy

flake8:
  stage: lint
  script:
    - flake8 hloenv/ --count --show-source --statistics

cpplint:
  stage: lint
  script:
    - cpplint --root=. --recursive hloenv/

clang-format:
  stage: lint
  script:
    - clang-format-11 --style=Google -i $(find hloenv/ -regex ".*\.\(proto\|cpp\|c\|cc\|cxx\|hpp\|h\|hxx\)$") -n -Werror

buildifier:
  stage: lint
  script:
    - buildifier -r -lint warn hloenv/


build_and_test:
  stage: build_and_test
  script:
    - mkdir ./dist
    - bazel build --remote_cache=http://bazel-cache-http.ai.seacloud.garenanow.com //:setup
    - bazel run --remote_cache=http://bazel-cache-http.ai.seacloud.garenanow.com //:setup
    - bazel test --test_env=GITLAB_CI="True" --test_output=all --remote_cache=http://bazel-cache-http.ai.seacloud.garenanow.com //tests/...
    - ls bazel-bin/setup.runfiles/org_hloenv/dist/*.whl
    - cp "$(ls bazel-bin/setup.runfiles/org_hloenv/dist/*.whl)" "./dist/"
    - touch "./dist/$CI_COMMIT_SHA"
    - tar cf dist.tar dist
  artifacts:
    paths:
      - dist.tar

whl:
  stage: deploy
  only:
    - main
  before_script:
    - pip3 install twine
  script:
    - /tools/deploy_to_pypi.sh dist.tar
