// Copyright 2021 Garena Online Private Limited

#ifndef ALTGRAPH_SCHEDULE_PASS_DEFS_H_
#define ALTGRAPH_SCHEDULE_PASS_DEFS_H_

#include <map>
#include <string>

#include "altgraph/hlo_pass_defs.h"

enum class PassType {
  // -------------------------------------
  //   GPU PASSES
  // -------------------------------------
  AlgebraicSimplifier,
  AllGatherBroadcastReorder,
  AllGatherCombiner,
  AllReduceBlueConnect,
  AllReduceCombiner,
  AllReduceContiguous,
  AllReduceFolder,
  AllReduceReassociate,
  AllToAllDecomposer,
  AsyncCollectiveCreator,
  BFloat16Normalization,
  BatchNormExpander,
  BitcastDtypesExpander,
  CallInliner,
  CollectivesScheduleLinearizer,
  ComparisonExpander,
  ConditionalCanonicalizer,
  ConditionalSimplifier,
  Convolution4DExpander,
  DotDecomposer,
  DotMerger,
  DynamicDimensionSimplifier,
  DynamicIndexSplitter,
  DynamicPadder,
  EighExpander,
  FlattenCallGraph,
  GatherExpander,
  GpuLayoutAssignment,
  GpuScatterExpander,
  HloCSE,
  HloConstantFolding,
  HloDCE,
  HloVerifier,
  LogisticExpander,
  OperandUpcaster,
  OptimizationBarrierExpander,
  QrExpander,
  RealImagExpander,
  ReduceScatterCombiner,
  ReduceScatterCreator,
  ReshapeMover,
  ResultCaster,
  RngBitGeneratorExpander,
  RngExpander,
  ScatterExpander,
  ShardingPropagation,
  ShardingRemover,
  SliceSinker,
  SortSimplifier,
  StableSortExpander,
  StatefulRngSpmdPartitioner,
  TransposeFolding,
  TupleSimplifier,
  WhileLoopConstantSinking,
  WhileLoopSimplifier,
  WhileLoopTripCountAnnotator,
  ZeroSizedHloElimination,
  // -------------------------------------
  //   OTHERS
  // -------------------------------------
  AliasPassthroughParams,
  AllGatherDecomposer,
  AllReduceSimplifier,
  ArCrsCombiner,
  BFloat16ConversionFolding,
  BFloat16MixedPrecisionRemoval,
  BFloat16Propagation,
  BarBlowerUpper,
  BatchDotSimplification,
  CanonicalizeAllGatherForCSE,
  CholeskyExpander,
  ConditionalCodeMotion,
  ConditionalToSelect,
  ControlDepRemover,
  ConvCanonicalization,
  ConvertOperandFolding,
  ConvolutionGroupConverter,
  CopyInsertion,
  CpuInstructionFusion,
  CpuLayoutAssignment,
  CublasPadForGemms,
  CudnnFusedConvRewriter,
  CudnnPadForConvolutions,
  CudnnVectorizeConvolutions,
  Defuser,
  Despecializer,
  DryModeOff,
  DryModeOn,
  FooToBarModulePass,
  FusionBitcastLift,
  FusionMerger,
  GemmAlgorithmPicker,
  GemmBroadcastFoldingRewriter,
  GemmRewriter,
  GeneralFusion,
  GpuConvAlgorithmPicker,
  GpuConvPaddingLegalization,
  GpuConvRewriter,
  GpuHorizontalInputFusion,
  GpuHorizontalLoopFusion,
  GpuInstructionFusion,
  GpuMultiOutputFusion,
  GpuSanitizeConstantNames,
  GpuTreeReductionRewriter,
  GpusolverRewriter,
  HloControlFlowFlattening,
  HloDescheduler,
  HloDomainIsolator,
  HloDomainRemover,
  HloDomainVerifier,
  HloElementTypeConverter,
  HloGetDimensionSizeRewriter,
  HloMemoryScheduler,
  HloModuleDCE,
  HloRematerialization,
  HloSubcomputationUnification,
  HloTrivialScheduler,
  IndexedArrayAnalysisPrinterPass,
  InstructionFusion,
  InstructionFusionForTesting,
  LayoutAssignment,
  LoopScheduleLinearizer,
  MapInliner,
  MemorySpacePropagation,
  MultiOutputFusion,
  OpExpanderPass,
  OperandsMustBeTheSameLayoutAssignment,
  OptimizeInputOutputBufferAlias,
  ParallelTaskAssigner,
  ReduceScatterDecomposer,
  ReductionDegenerateDimRemover,
  ReductionDimensionGrouper,
  ReductionLayoutNormalizer,
  ReductionSplitter,
  RootInstructionSinker,
  ScheduleAwareCollectiveOpsCSE,
  SpaceToBatchConverter,
  SpmdPartitioner,
  TopkRewriter,
  TreeReductionRewriter,
  TriangularSolveExpander,
  TriangularSolveRewriter,
  VariadicOpSplitter,
  WhileLoopAllReduceCodeMotion,
  WhileLoopConcatCodeMotion,
  WhileLoopExpensiveInvariantCodeMotion,
  WhileLoopInvariantCodeMotion,
  PassTypeMaxEnum,
};

std::map<std::string, PassType> altgraph_MapStringToPassType = {
    // -------------------------------------
    //   GPU PASSES
    // -------------------------------------
    {"AlgebraicSimplifier", PassType::AlgebraicSimplifier},
    {"AllGatherBroadcastReorder", PassType::AllGatherBroadcastReorder},
    {"AllGatherCombiner", PassType::AllGatherCombiner},
    {"AllReduceBlueConnect", PassType::AllReduceBlueConnect},
    {"AllReduceCombiner", PassType::AllReduceCombiner},
    {"AllReduceContiguous", PassType::AllReduceContiguous},
    {"AllReduceFolder", PassType::AllReduceFolder},
    {"AllReduceReassociate", PassType::AllReduceReassociate},
    {"AllToAllDecomposer", PassType::AllToAllDecomposer},
    {"AsyncCollectiveCreator", PassType::AsyncCollectiveCreator},
    {"BFloat16Normalization", PassType::BFloat16Normalization},
    {"BatchNormExpander", PassType::BatchNormExpander},
    {"BitcastDtypesExpander", PassType::BitcastDtypesExpander},
    {"CallInliner", PassType::CallInliner},
    {"CollectivesScheduleLinearizer", PassType::CollectivesScheduleLinearizer},
    {"ComparisonExpander", PassType::ComparisonExpander},
    {"ConditionalCanonicalizer", PassType::ConditionalCanonicalizer},
    {"ConditionalSimplifier", PassType::ConditionalSimplifier},
    {"Convolution4DExpander", PassType::Convolution4DExpander},
    {"DotDecomposer", PassType::DotDecomposer},
    {"DotMerger", PassType::DotMerger},
    {"DynamicDimensionSimplifier", PassType::DynamicDimensionSimplifier},
    {"DynamicIndexSplitter", PassType::DynamicIndexSplitter},
    {"DynamicPadder", PassType::DynamicPadder},
    {"EighExpander", PassType::EighExpander},
    {"FlattenCallGraph", PassType::FlattenCallGraph},
    {"GatherExpander", PassType::GatherExpander},
    {"GpuLayoutAssignment", PassType::GpuLayoutAssignment},
    {"GpuScatterExpander", PassType::GpuScatterExpander},
    {"HloCSE", PassType::HloCSE},
    {"HloConstantFolding", PassType::HloConstantFolding},
    {"HloDCE", PassType::HloDCE},
    {"HloVerifier", PassType::HloVerifier},
    {"LogisticExpander", PassType::LogisticExpander},
    {"OperandUpcaster", PassType::OperandUpcaster},
    {"OptimizationBarrierExpander", PassType::OptimizationBarrierExpander},
    {"QrExpander", PassType::QrExpander},
    {"RealImagExpander", PassType::RealImagExpander},
    {"ReduceScatterCombiner", PassType::ReduceScatterCombiner},
    {"ReduceScatterCreator", PassType::ReduceScatterCreator},
    {"ReshapeMover", PassType::ReshapeMover},
    {"ResultCaster", PassType::ResultCaster},
    {"RngBitGeneratorExpander", PassType::RngBitGeneratorExpander},
    {"RngExpander", PassType::RngExpander},
    {"ScatterExpander", PassType::ScatterExpander},
    {"ShardingPropagation", PassType::ShardingPropagation},
    {"ShardingRemover", PassType::ShardingRemover},
    {"SliceSinker", PassType::SliceSinker},
    {"SortSimplifier", PassType::SortSimplifier},
    {"StableSortExpander", PassType::StableSortExpander},
    {"StatefulRngSpmdPartitioner", PassType::StatefulRngSpmdPartitioner},
    {"TransposeFolding", PassType::TransposeFolding},
    {"TupleSimplifier", PassType::TupleSimplifier},
    {"WhileLoopConstantSinking", PassType::WhileLoopConstantSinking},
    {"WhileLoopSimplifier", PassType::WhileLoopSimplifier},
    {"WhileLoopTripCountAnnotator", PassType::WhileLoopTripCountAnnotator},
    {"ZeroSizedHloElimination", PassType::ZeroSizedHloElimination},
    // -------------------------------------
    //   OTHERS
    // -------------------------------------
    {"AliasPassthroughParams", PassType::AliasPassthroughParams},
    {"AllGatherDecomposer", PassType::AllGatherDecomposer},
    {"AllReduceSimplifier", PassType::AllReduceSimplifier},
    {"ArCrsCombiner", PassType::ArCrsCombiner},
    {"BFloat16ConversionFolding", PassType::BFloat16ConversionFolding},
    {"BFloat16MixedPrecisionRemoval", PassType::BFloat16MixedPrecisionRemoval},
    {"BFloat16Propagation", PassType::BFloat16Propagation},
    {"BarBlowerUpper", PassType::BarBlowerUpper},
    {"BatchDotSimplification", PassType::BatchDotSimplification},
    {"CanonicalizeAllGatherForCSE", PassType::CanonicalizeAllGatherForCSE},
    {"CholeskyExpander", PassType::CholeskyExpander},
    {"ConditionalCodeMotion", PassType::ConditionalCodeMotion},
    {"ConditionalToSelect", PassType::ConditionalToSelect},
    {"ControlDepRemover", PassType::ControlDepRemover},
    {"ConvCanonicalization", PassType::ConvCanonicalization},
    {"ConvertOperandFolding", PassType::ConvertOperandFolding},
    {"ConvolutionGroupConverter", PassType::ConvolutionGroupConverter},
    {"CopyInsertion", PassType::CopyInsertion},
    {"CpuInstructionFusion", PassType::CpuInstructionFusion},
    {"CpuLayoutAssignment", PassType::CpuLayoutAssignment},
    {"CublasPadForGemms", PassType::CublasPadForGemms},
    {"CudnnFusedConvRewriter", PassType::CudnnFusedConvRewriter},
    {"CudnnPadForConvolutions", PassType::CudnnPadForConvolutions},
    {"CudnnVectorizeConvolutions", PassType::CudnnVectorizeConvolutions},
    {"Defuser", PassType::Defuser},
    {"Despecializer", PassType::Despecializer},
    {"DryModeOff", PassType::DryModeOff},
    {"DryModeOn", PassType::DryModeOn},
    {"FooToBarModulePass", PassType::FooToBarModulePass},
    {"FusionBitcastLift", PassType::FusionBitcastLift},
    {"FusionMerger", PassType::FusionMerger},
    {"GemmAlgorithmPicker", PassType::GemmAlgorithmPicker},
    {"GemmBroadcastFoldingRewriter", PassType::GemmBroadcastFoldingRewriter},
    {"GemmRewriter", PassType::GemmRewriter},
    {"GeneralFusion", PassType::GeneralFusion},
    {"GpuConvAlgorithmPicker", PassType::GpuConvAlgorithmPicker},
    {"GpuConvPaddingLegalization", PassType::GpuConvPaddingLegalization},
    {"GpuConvRewriter", PassType::GpuConvRewriter},
    {"GpuHorizontalInputFusion", PassType::GpuHorizontalInputFusion},
    {"GpuHorizontalLoopFusion", PassType::GpuHorizontalLoopFusion},
    {"GpuInstructionFusion", PassType::GpuInstructionFusion},
    {"GpuMultiOutputFusion", PassType::GpuMultiOutputFusion},
    {"GpuSanitizeConstantNames", PassType::GpuSanitizeConstantNames},
    {"GpuTreeReductionRewriter", PassType::GpuTreeReductionRewriter},
    {"GpusolverRewriter", PassType::GpusolverRewriter},
    {"HloControlFlowFlattening", PassType::HloControlFlowFlattening},
    {"HloDescheduler", PassType::HloDescheduler},
    {"HloDomainIsolator", PassType::HloDomainIsolator},
    {"HloDomainRemover", PassType::HloDomainRemover},
    {"HloDomainVerifier", PassType::HloDomainVerifier},
    {"HloElementTypeConverter", PassType::HloElementTypeConverter},
    {"HloGetDimensionSizeRewriter", PassType::HloGetDimensionSizeRewriter},
    {"HloMemoryScheduler", PassType::HloMemoryScheduler},
    {"HloModuleDCE", PassType::HloModuleDCE},
    {"HloRematerialization", PassType::HloRematerialization},
    {"HloSubcomputationUnification", PassType::HloSubcomputationUnification},
    {"HloTrivialScheduler", PassType::HloTrivialScheduler},
    {"IndexedArrayAnalysisPrinterPass",
     PassType::IndexedArrayAnalysisPrinterPass},
    {"InstructionFusion", PassType::InstructionFusion},
    {"InstructionFusionForTesting", PassType::InstructionFusionForTesting},
    {"LayoutAssignment", PassType::LayoutAssignment},
    {"LoopScheduleLinearizer", PassType::LoopScheduleLinearizer},
    {"MapInliner", PassType::MapInliner},
    {"MemorySpacePropagation", PassType::MemorySpacePropagation},
    {"MultiOutputFusion", PassType::MultiOutputFusion},
    {"OpExpanderPass", PassType::OpExpanderPass},
    {"OperandsMustBeTheSameLayoutAssignment",
     PassType::OperandsMustBeTheSameLayoutAssignment},
    {"OptimizeInputOutputBufferAlias",
     PassType::OptimizeInputOutputBufferAlias},
    {"ParallelTaskAssigner", PassType::ParallelTaskAssigner},
    {"ReduceScatterDecomposer", PassType::ReduceScatterDecomposer},
    {"ReductionDegenerateDimRemover", PassType::ReductionDegenerateDimRemover},
    {"ReductionDimensionGrouper", PassType::ReductionDimensionGrouper},
    {"ReductionLayoutNormalizer", PassType::ReductionLayoutNormalizer},
    {"ReductionSplitter", PassType::ReductionSplitter},
    {"RootInstructionSinker", PassType::RootInstructionSinker},
    {"ScheduleAwareCollectiveOpsCSE", PassType::ScheduleAwareCollectiveOpsCSE},
    {"SpaceToBatchConverter", PassType::SpaceToBatchConverter},
    {"SpmdPartitioner", PassType::SpmdPartitioner},
    {"TopkRewriter", PassType::TopkRewriter},
    {"TreeReductionRewriter", PassType::TreeReductionRewriter},
    {"TriangularSolveExpander", PassType::TriangularSolveExpander},
    {"TriangularSolveRewriter", PassType::TriangularSolveRewriter},
    {"VariadicOpSplitter", PassType::VariadicOpSplitter},
    {"WhileLoopAllReduceCodeMotion", PassType::WhileLoopAllReduceCodeMotion},
    {"WhileLoopConcatCodeMotion", PassType::WhileLoopConcatCodeMotion},
    {"WhileLoopExpensiveInvariantCodeMotion",
     PassType::WhileLoopExpensiveInvariantCodeMotion},
    {"WhileLoopInvariantCodeMotion", PassType::WhileLoopInvariantCodeMotion},
};

#endif  // ALTGRAPH_SCHEDULE_PASS_DEFS_H_
